enduser/feature/enhance_navigation
TheChance101/beep-beep pull request #117
Opened 2023-08-16 16:19 UTC by aya-seif

2023-08-16 16:24 UTC, devsadeq approved these changes

2023-08-16 16:28 UTC, HaidyAbuGom3a approved these changes

2023-08-16 21:15 UTC, Mohammed-Alhams requested changes

2023-08-16 21:15 UTC, Mohammed-Alhams commented on client_end_user/shared/src/commonMain/kotlin/presentation/screens/HomeViewModel.kt
> +class HomeViewModel : StateScreenModel<HomeUiState>(HomeUiState()), KoinComponent {
There is actually no requirement to inherit the KoinComponent in this particular situation.
```suggestion
class HomeViewModel : StateScreenModel<HomeUiState>(HomeUiState()) {
```

2023-08-16 21:15 UTC, Mohammed-Alhams commented on client_end_user/shared/src/commonMain/kotlin/app/di/AppModule.kt
> +            viewModelModule,
It seems like the dataSourceModule is missing from the modules block.
```suggestion
        modules(
            networkModule,
            gatewayModule,
            useCaseModule,
            viewModelModule,
            dataSourceModule
```

2023-08-16 21:20 UTC, Mohammed-Alhams commented on client_end_user/shared/src/commonMain/kotlin/presentation/screens/HomeScreenContent.kt
> +class HomeScreen : Screen, KoinComponent {
Sorry, I can see that you might be facing some trouble if not inherit it. To utilize the inject function, you'll need to inherit it.

2023-08-17 13:55 UTC, Mohammed-Alhams approved these changes

2023-08-17 14:05 UTC, merged