identity/feature/address
TheChance101/beep-beep pull request #13
Opened 2023-07-31 21:14 UTC by mustafa-sab3alarab

1- Move dir of entity package to domain package
2- Create address gateway
3- Create all usecases needed to crud operations
4- Create mapper to convert entity to collection

2023-07-31 21:44 UTC, devsadeq approved these changes
LGTM

2023-07-31 21:44 UTC, devsadeq commented on service_identity/src/main/kotlin/org/thechance/service_identity/api/endpoints/Address.kt
> +fun Route.addressRoutes() {
File name doesn't match this function

2023-07-31 21:44 UTC, devsadeq commented on service_identity/src/main/kotlin/org/thechance/service_identity/api/endpoints/Address.kt
> +    get("/address/{id}") {
Create route that wrap all the methods to prevent duplication

2023-07-31 21:44 UTC, ay0o5h approved these changes
LGTM

2023-07-31 22:44 UTC, Shehab-m commented on service_identity/src/main/kotlin/org/thechance/service_identity/data/MongoDataBase.kt
> +class MongoDataBase(client : MongoClient) {
For consistency in naming, it would be better renaming MongoDataBase to DataBaseContainer.

2023-07-31 23:03 UTC, Asiasama710 requested changes

2023-08-01 15:14 UTC, ay0o5h approved these changes

2023-08-01 16:10 UTC, Asiasama710 approved these changes

2023-08-01 16:11 UTC, merged