feature/dashboard/theme_switching
TheChance101/beep-beep pull request #232
Opened 2023-08-28 16:06 UTC by aya-seif

add theme screen model 
add user theme configuration 
handle theme switching

2023-08-28 16:11 UTC, HaidyAbuGom3a approved these changes

2023-08-28 16:12 UTC, Mohammed-Alhams approved these changes

2023-08-28 18:13 UTC, ay0o5h approved these changes

2023-08-30 15:08 UTC, Asiasama710 requested changes

2023-08-30 15:08 UTC, Asiasama710 commented on client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/main/MainContainer.kt
>                  isDarkMode = isDarkMode
u can use state directly
```kotlin
isDarkMode = state.isDarkMode
```

2023-08-30 22:43 UTC, Asiasama710 approved these changes

2023-08-30 22:45 UTC, merged