refactor: dto models
TheChance101/beep-beep pull request #249
Opened 2023-08-29 13:32 UTC by Saif-Alhaider

- add serializable annotation to each dto model
- made all values nullable

* because we are using DataWrapperDto i didn't change its attributes for now

2023-08-29 14:19 UTC, Asiasama710 requested changes

2023-08-29 14:19 UTC, Asiasama710 commented on client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/model/AdminDto.kt
> +data class AdminDto(
Delete it, it is not used anyway

2023-08-29 14:19 UTC, Asiasama710 commented on client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/model/ServerResponse.kt
>  data class ServerResponse<T>(
change name to BaseResponse

2023-08-30 17:52 UTC, Saif-Alhaider commented on client_dashboard/common/src/commonMain/kotlin/org/thechance/common/data/remote/model/AdminDto.kt
> +data class AdminDto(
resolved

2023-08-30 17:59 UTC, Asiasama710 approved these changes

2023-08-30 18:27 UTC, mustafa-sab3alarab approved these changes

2023-09-01 15:17 UTC, merged