feature/dashboard/users-search
TheChance101/beep-beep pull request #256
Opened 2023-08-30 07:49 UTC by devsadeq

- Moved the fake user list from the getUsers function to the gateway class scope, enabling its reuse.
- Created functions to retrieve filtered users based on their full names or usernames, with pagination.
- Handled indicator interaction and adjusted page interactions to fetch filtered users according to user search input.
- Removed unnecessary code from the screen model.

2023-08-30 08:04 UTC, ay0o5h requested changes

2023-08-30 08:04 UTC, ay0o5h commented on client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/users/UserScreenModel.kt
>      override fun onSearchInputChange(text: String) {
use debounce with search

2023-08-30 16:43 UTC, ay0o5h approved these changes

2023-09-01 14:54 UTC, aya-seif approved these changes

2023-09-01 16:05 UTC, merged