add permission CRUD
TheChance101/beep-beep pull request #26
Opened 2023-08-02 20:13 UTC by Elboray

please make review and send me to do any refactor

2023-08-02 21:23 UTC, ay0o5h commented
please resolve conflict

2023-08-03 00:30 UTC, Asiasama710 requested changes

2023-08-03 00:30 UTC, Asiasama710 commented on service_identity/src/main/kotlin/org/thechance/service_identity/data/geteway/PermissionGatewayImp.kt
> +            permissionCollection.deleteOne(Filters.eq("_id", objectId))
use soft delete by using `updateOne `instead of `deleteOne` and filter by isDelete

2023-08-03 00:30 UTC, Asiasama710 commented on service_identity/src/main/kotlin/org/thechance/service_identity/api/endpoints/permissionRoutes.kt
> +            val permission = permissionUseCasesContainer.getPermission.invoke(permissionId).toPermissionDto()
Is there a need for calling `invoke `here couldn't it just be normal brantheses invocation

2023-08-03 00:30 UTC, Asiasama710 commented on service_identity/src/main/kotlin/org/thechance/service_identity/domain/usecases/permission/CreatePermissionUseCaseImp.kt
> +    private fun checkValidation(permission: Permission) {
why function is empty?

2023-08-03 08:37 UTC, Asiasama710 approved these changes
well done 👏 , but please resolve conflict

2023-08-03 09:48 UTC, devsadeq commented on service_identity/src/main/kotlin/org/thechance/service_identity/api/endpoints/permissionRoutes.kt
> +        delete("/permissions/{permissionId}") {
It looks like you've duplicated the word "permissions" unnecessarily. Instead, it should be just ```delete("/{permissionId}")``` without the repetition.

2023-08-03 09:48 UTC, devsadeq commented on service_identity/src/main/kotlin/org/thechance/service_identity/api/endpoints/permissionRoutes.kt
> +        }
For better consistency and clarity, let's use the same parameter name 'permissionId' in the GET method, just like in the other methods. Also, it's better to handle invalid parameters consistently, either by returning a response or throwing an exception.

2023-08-03 11:19 UTC, Elboray commented
> well done 👏 , but please resolve conflict

thanks

2023-08-03 11:48 UTC, Elboray commented
> please resolve conflict

you can check now

2023-08-03 12:45 UTC, Shehab-m approved these changes

2023-08-03 13:09 UTC, Shehab-m commented on service_identity/src/main/kotlin/org/thechance/service_identity/domain/entity/Permission.kt
> +    val isDeleted: Boolean? = null
i think we shouldn't use nullable value for isDeleted field instead use default false value

2023-08-03 14:00 UTC, Asiasama710 approved these changes

2023-08-03 20:23 UTC, devsadeq approved these changes

2023-08-03 21:17 UTC, merged