dashboard/feature/add_cuisine
TheChance101/beep-beep pull request #278
Opened 2023-08-31 12:29 UTC by mujtaba912

implement add cuisines dialog in restaurant screen in client dashboard which have:
- get all cuisines 
- add a cuisine
- delete a cuisine

https://github.com/TheChance101/beep-beep/assets/123612093/961a2d9e-be26-40ca-aef2-65c6d0d069ef

2023-09-01 05:05 UTC, devsadeq approved these changes
LGTM

2023-09-01 05:05 UTC, devsadeq commented on client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantInteractionListener.kt
> +
Make your functions names more consistence plz.

2023-09-01 08:02 UTC, mujtaba912 commented on client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantInteractionListener.kt
> +
done

2023-09-01 17:27 UTC, Karrar-Mohammed commented on client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreenModel.kt
> +    override fun onAddCuisineDialogDeleteClicked(cuisineName: String) {
fix this name

2023-09-01 17:28 UTC, Karrar-Mohammed commented on client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreenModel.kt
> +    override fun onAddCuisineDialogCloseRequest() {
fix this name

2023-09-01 17:29 UTC, Karrar-Mohammed commented on client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreenModel.kt
> +    override fun onAddCuisineDialogAddClicked() {
fix this name

2023-09-01 17:29 UTC, Karrar-Mohammed commented on client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantScreenModel.kt
> +    override fun onAddCuisineDialogCuisineNameChange(cuisineName: String) {
fix this name

2023-09-01 17:33 UTC, Karrar-Mohammed commented on client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantUiState.kt
> +    val cuisinesSize: Int = 0
we don't need this parameter

2023-09-01 17:36 UTC, Karrar-Mohammed requested changes

2023-09-01 17:36 UTC, Karrar-Mohammed commented on client_dashboard/common/src/commonMain/kotlin/org/thechance/common/presentation/restaurant/RestaurantUiState.kt
> +    val cuisinesSize: Int = 0
we don't need this parameter we should delete it

2023-09-04 16:47 UTC, Karrar-Mohammed approved these changes

2023-09-04 16:48 UTC, merged