Meals Preference Screen
TheChance101/beep-beep pull request #378
Opened 2023-09-11 01:09 UTC by ahmednasserzaza

2023-09-11 06:09 UTC, NadaFeteiha requested changes
Great work! But, let's make sure that the user can't go back to this screen.
also, there's an error on IOS looks like the font is not found " Missing resource with path: font/roboto_medium.ttf"

<img width="1291" alt="Screenshot 2023-09-10 at 11 09 04 PM" src="https://github.com/TheChance101/beep-beep/assets/34461597/80dfc787-b290-43dc-a69f-53a0a5fc7408">

2023-09-11 19:56 UTC, mustafa-sab3alarab approved these changes

2023-09-11 20:02 UTC, NadaFeteiha approved these changes

2023-09-11 21:12 UTC, ay0o5h approved these changes

2023-09-12 04:37 UTC, Youssef-Ramadan-Y approved these changes

2023-09-12 05:47 UTC, merged