Change Langauge
TheChance101/beep-beep pull request #397
Opened 2023-09-15 12:06 UTC by mustafa-sab3alarab

Tasks:

Handle hard-coded strings used in screen models and find a proper way to display these messages.
Implement language localization in the app and apply it after the user selects their preferred language.
Create an IStringResources interface that contains all string values. Implement this interface for languages such as Arabic, English, ArabicSY, ArabicEG, etc. Additionally, in the dependency injection (DI) setup, if no language is selected from the Preferred Language Screen, set "en" as the default language to provide all screen models that use IStringResources.

For Composable, I've created a LocalizationManager that includes two functions:

1 - getLayoutDirection() - This function is used to change the layout direction based on the selected language code.

2 - getStringResources() - This function returns an instance of IStringResources depending on the selected language code.

2023-09-16 09:39 UTC, mosayed01 approved these changes

2023-09-16 10:28 UTC, ay0o5h requested changes

2023-09-16 10:28 UTC, ay0o5h commented on client_end_user/shared/src/commonMain/kotlin/App.kt
> +    val localConfigurationGateway = LocalConfigurationGateway(getKoin().get())
there is an AppModelScreen u can get languged code instad of call gateway inside app check it in - presentetion -> app dirctory

2023-09-16 11:21 UTC, ay0o5h approved these changes
well done

2023-09-16 11:21 UTC, ay0o5h commented on client_end_user/shared/src/commonMain/kotlin/domain/usecase/ManageUserUseCase.kt
> +    override suspend fun getUserLanguageCode(): String {
there is a    MangeLanguageUseCase u can use  getLanguageCode using it

2023-09-16 12:15 UTC, ahmednasserzaza approved these changes

2023-09-18 01:57 UTC, HaidyAbuGom3a approved these changes

2023-09-18 17:48 UTC, merged