Api gatewat/feature/add get and update user info
TheChance101/beep-beep pull request #441
Opened 2023-09-21 12:50 UTC by ay0o5h

2023-09-22 00:13 UTC, NadaFeteiha requested changes

2023-09-22 00:13 UTC, NadaFeteiha commented on api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/UserDetailsDto.kt
> +data class UserDetailsDto(
why you didn't use UserDto already in the API-gateway model?

2023-09-22 00:13 UTC, NadaFeteiha commented on api_gateway/src/main/kotlin/org/thechance/api_gateway/data/service/IdentityService.kt
> +    ): UserDetailsDto {
The username and email are not allowed to be updated

2023-09-22 00:13 UTC, NadaFeteiha commented on api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/UserRoute.kt
> +                val id = call.parameters["id"] ?: ""
the ID should be extracted from the token.

2023-09-22 00:13 UTC, NadaFeteiha commented on api_gateway/src/main/kotlin/org/thechance/api_gateway/endpoints/UserRoute.kt
> +            put("profile/{id}") {
The ID should be extracted from the token.

2023-09-22 15:12 UTC, mosayed01 commented on api_gateway/src/main/kotlin/org/thechance/api_gateway/data/model/UserDto.kt
> +    @SerialName("currency") val currency: String? = null,z
```suggestion
    @SerialName("currency") val currency: String? = null,
```

2023-09-23 01:07 UTC, mosayed01 approved these changes

2023-09-23 15:52 UTC, NadaFeteiha requested changes
<img width="1074" alt="Screenshot 2023-09-23 at 8 50 43 AM" src="https://github.com/TheChance101/beep-beep/assets/34461597/4ca052b8-3dc4-428b-978b-e9c022f96eb6">

please test the branch and be sure that is run before making it ready for review. 
+ Add the endpoints in the description

2023-09-25 21:34 UTC, devsadeq approved these changes

2023-09-27 22:26 UTC, aya-seif approved these changes

2023-09-28 07:57 UTC, NadaFeteiha approved these changes

2023-09-28 08:47 UTC, merged