implement cart screen
TheChance101/beep-beep pull request #448
Opened 2023-09-22 17:55 UTC by HaidyAbuGom3a

- add fake data
- add cart composables

2023-09-22 23:00 UTC, NadaFeteiha commented
<img width="355" alt="Screenshot 2023-09-22 at 3 53 50 PM" src="https://github.com/TheChance101/beep-beep/assets/34461597/fef70f99-0970-44c8-b513-9cfe8bcd841a">

please make the above button in the home navigate to the cart screen.
and call getNavigationBarPadding() in your screen to avoid this behavior it's already in main 

<img width="437" alt="Screenshot 2023-09-22 at 3 59 32 PM" src="https://github.com/TheChance101/beep-beep/assets/34461597/140b2b0f-8216-4ce1-a213-3b124b394893">

2023-09-22 23:00 UTC, NadaFeteiha requested changes
<img width="355" alt="Screenshot 2023-09-22 at 3 53 50 PM" src="https://github.com/TheChance101/beep-beep/assets/34461597/fef70f99-0970-44c8-b513-9cfe8bcd841a">

please make the above button in the home navigate to the cart screen.
and call getNavigationBarPadding() in your screen to avoid this behavior it's already in main 

<img width="437" alt="Screenshot 2023-09-22 at 3 59 32 PM" src="https://github.com/TheChance101/beep-beep/assets/34461597/140b2b0f-8216-4ce1-a213-3b124b394893">

2023-09-23 03:56 UTC, hassanwasfy approved these changes

2023-09-23 16:45 UTC, hassanwasfy approved these changes

2023-09-23 16:54 UTC, mosayed01 approved these changes

2023-09-23 17:22 UTC, NadaFeteiha approved these changes

2023-09-23 17:37 UTC, ay0o5h approved these changes

2023-09-23 17:39 UTC, merged