backend/feature/remove_related_data_when_delete_user
TheChance101/beep-beep pull request #451
Opened 2023-09-23 21:14 UTC by mosayed01

2023-09-24 16:44 UTC, mosayed01 commented on service_restaurant/src/main/kotlin/org/thechance/service_restaurant/data/gateway/RestaurantGateway.kt
> +
```suggestion
```

2023-09-25 06:07 UTC, NadaFeteiha requested changes
return true but restaurants still have not deleted 
<img width="757" alt="Screenshot 2023-09-24 at 11 04 44 PM" src="https://github.com/TheChance101/beep-beep/assets/34461597/b8d41fbe-46c9-47f0-a7c9-0f456115a800">

<img width="637" alt="Screenshot 2023-09-24 at 11 05 09 PM" src="https://github.com/TheChance101/beep-beep/assets/34461597/88137d36-acca-497a-8957-1f5207792ddc">

2023-09-25 06:18 UTC, mosayed01 commented
> return true but restaurants still have not deleted 
> <img width="757" alt="Screenshot 2023-09-24 at 11 04 44 PM" src="https://github.com/TheChance101/beep-beep/assets/34461597/b8d41fbe-46c9-47f0-a7c9-0f456115a800">
> 
> <img width="637" alt="Screenshot 2023-09-24 at 11 05 09 PM" src="https://github.com/TheChance101/beep-beep/assets/34461597/88137d36-acca-497a-8957-1f5207792ddc">
> 

@NadaFeteiha The deletion depend on owner user name but this document doesn't have ownerUsername attribute

2023-09-25 08:49 UTC, ahmednasserzaza approved these changes

2023-09-25 15:21 UTC, ay0o5h approved these changes

2023-09-25 16:08 UTC, NadaFeteiha approved these changes

2023-09-25 21:28 UTC, devsadeq approved these changes

2023-09-25 21:35 UTC, merged