dashboard/feature/refactor_data_packages_structure
TheChance101/beep-beep pull request #454
Opened 2023-09-24 15:20 UTC by aya-seif

2023-09-24 15:21 UTC, hassanwasfy approved these changes

2023-09-24 16:59 UTC, Karrar-Mohammed requested changes, later dismissed
i don't think this is how we want make the data packages, let's have a call to discuss it later

2023-09-25 21:30 UTC, devsadeq approved these changes

2023-09-26 14:20 UTC, hassanwasfy approved these changes

2023-09-27 00:27 UTC, Asiasama710 approved these changes

2023-09-27 17:20 UTC, ay0o5h approved these changes

2023-09-27 22:17 UTC, merged