backend/get-active-orders-for-user
TheChance101/beep-beep pull request #514
Opened 2023-10-16 16:56 UTC by ahmednasserzaza

add new endpoint to get active orders for specific user.

2023-10-16 17:08 UTC, ay0o5h approved these changes

2023-10-16 17:58 UTC, NadaFeteiha approved these changes

2023-10-18 19:41 UTC, mosayed01 approved these changes

2023-10-18 19:48 UTC, devsadeq approved these changes

2023-10-19 17:55 UTC, NadaFeteiha requested changes

2023-10-19 17:55 UTC, NadaFeteiha commented on service_taxi/src/main/kotlin/org/thechance/service_taxi/api/endpoints/TripRoutes.kt
> +            val userId = parameters["userId"] ?: throw MissingParameterException()
Why is the userId parameter required, given that the user creating the trip is already known? Additionally, relying on the delivery mechanism to send the correct userId is not secure.

2023-10-21 18:18 UTC, NadaFeteiha approved these changes

2023-10-21 18:34 UTC, merged